"""
GSVAI Enterprise AI Model Service.

Manages the persistent Oracle Database model registry (GSVAI_AI_MODELS).
Provides:
- Database table initialization and safe seeding
- Model retrieval with live availability & health status
- Atomic primary and fallback assignments
- Disable and delete rule enforcement
- Live model testing (Groq and Ollama) with latency measurement
- Audit logging of all model configuration mutations
- Zero secret exposure
"""

import os
import time
from typing import Any, Dict, List, Optional
import oracledb
import requests
from dotenv import load_dotenv

from services.oracle_db_service import get_connection
from services.auth_rbac_service import log_audit_event

load_dotenv()

SUPPORTED_PROVIDERS = ["Groq", "Ollama"]
SUPPORTED_MODEL_TYPES = ["LLM"]


def table_exists(cursor, table_name: str) -> bool:
    """Checks whether a table exists in the current Oracle schema."""
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM user_tables
        WHERE table_name = :table_name
        """,
        {"table_name": table_name.upper()},
    )
    return cursor.fetchone()[0] > 0


def ensure_ai_models_table() -> None:
    """
    Initializes the GSVAI_AI_MODELS table if not present, and seeds
    the current production architecture (Groq primary, Ollama fallback)
    without overwriting existing data.
    """
    conn = get_connection()
    cursor = conn.cursor()
    try:
        if not table_exists(cursor, "GSVAI_AI_MODELS"):
            cursor.execute(
                """
                CREATE TABLE GSVAI_AI_MODELS (
                    MODEL_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    PROVIDER         VARCHAR2(50) NOT NULL,
                    MODEL_NAME       VARCHAR2(255) NOT NULL,
                    MODEL_TYPE       VARCHAR2(50) DEFAULT 'LLM' NOT NULL,
                    RUNTIME_TYPE     VARCHAR2(50) DEFAULT 'API' NOT NULL,
                    ENABLED          NUMBER(1) DEFAULT 1 NOT NULL,
                    PRIORITY         NUMBER DEFAULT 1 NOT NULL,
                    IS_PRIMARY       NUMBER(1) DEFAULT 0 NOT NULL,
                    IS_FALLBACK      NUMBER(1) DEFAULT 0 NOT NULL,
                    TEMPERATURE      NUMBER(4, 2) DEFAULT 0.20,
                    MAX_TOKENS       NUMBER DEFAULT 4096,
                    DESCRIPTION      VARCHAR2(500),
                    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
                    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
                    CONSTRAINT UQ_GSVAI_MODELS_PROV_NAME UNIQUE (PROVIDER, MODEL_NAME)
                )
                """
            )
            print("GSVAI_AI_MODELS table created successfully.")

        # Seed initial models if not already present
        # 1. Primary: Groq openai/gpt-oss-20b
        cursor.execute(
            "SELECT COUNT(*) FROM GSVAI_AI_MODELS WHERE PROVIDER = 'Groq' AND MODEL_NAME = 'openai/gpt-oss-20b'"
        )
        if cursor.fetchone()[0] == 0:
            cursor.execute(
                """
                INSERT INTO GSVAI_AI_MODELS (
                    PROVIDER, MODEL_NAME, MODEL_TYPE, RUNTIME_TYPE,
                    ENABLED, PRIORITY, IS_PRIMARY, IS_FALLBACK,
                    TEMPERATURE, MAX_TOKENS, DESCRIPTION,
                    CREATED_AT, UPDATED_AT
                ) VALUES (
                    'Groq', 'openai/gpt-oss-20b', 'LLM', 'API',
                    1, 1, 1, 0,
                    0.20, 4096, 'Primary Enterprise Groq LLM API',
                    SYSTIMESTAMP, SYSTIMESTAMP
                )
                """
            )
            print("Seeded Groq openai/gpt-oss-20b into GSVAI_AI_MODELS.")

        # 2. Fallback: Ollama qwen3:0.6b
        cursor.execute(
            "SELECT COUNT(*) FROM GSVAI_AI_MODELS WHERE PROVIDER = 'Ollama' AND MODEL_NAME = 'qwen3:0.6b'"
        )
        if cursor.fetchone()[0] == 0:
            cursor.execute(
                """
                INSERT INTO GSVAI_AI_MODELS (
                    PROVIDER, MODEL_NAME, MODEL_TYPE, RUNTIME_TYPE,
                    ENABLED, PRIORITY, IS_PRIMARY, IS_FALLBACK,
                    TEMPERATURE, MAX_TOKENS, DESCRIPTION,
                    CREATED_AT, UPDATED_AT
                ) VALUES (
                    'Ollama', 'qwen3:0.6b', 'LLM', 'LOCAL',
                    1, 2, 0, 1,
                    0.20, 4096, 'Local Fallback Ollama LLM',
                    SYSTIMESTAMP, SYSTIMESTAMP
                )
                """
            )
            print("Seeded Ollama qwen3:0.6b into GSVAI_AI_MODELS.")

        conn.commit()
    except Exception as e:
        conn.rollback()
        raise e
    finally:
        cursor.close()
        conn.close()


def _check_ollama_online(timeout: float = 1.0) -> bool:
    """Probes local Ollama instance for live availability."""
    ollama_endpoint = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
    try:
        resp = requests.get(f"{ollama_endpoint.rstrip('/')}/api/tags", timeout=timeout)
        return resp.status_code == 200
    except Exception:
        return False


def get_ai_models() -> List[Dict[str, Any]]:
    """
    Retrieves all configured AI models from GSVAI_AI_MODELS,
    ordered by primary, priority, and model name.
    Enriches with live health status without exposing any secrets.
    """
    ensure_ai_models_table()
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            SELECT
                MODEL_ID,
                PROVIDER,
                MODEL_NAME,
                MODEL_TYPE,
                RUNTIME_TYPE,
                ENABLED,
                PRIORITY,
                IS_PRIMARY,
                IS_FALLBACK,
                TEMPERATURE,
                MAX_TOKENS,
                DESCRIPTION,
                CREATED_AT,
                UPDATED_AT
            FROM GSVAI_AI_MODELS
            ORDER BY IS_PRIMARY DESC, PRIORITY ASC, MODEL_NAME ASC
            """
        )
        rows = cursor.fetchall()

        groq_key_configured = bool(os.getenv("GROQ_API_KEY"))
        ollama_online = _check_ollama_online()

        models = []
        for r in rows:
            provider = r[1]
            enabled = bool(r[5])
            is_primary = bool(r[7])
            is_fallback = bool(r[8])

            # Evaluate meaningful health status
            if not enabled:
                status_label = "Disabled"
            elif provider == "Groq":
                status_label = "Active" if (is_primary and groq_key_configured) else ("Configured" if groq_key_configured else "Unconfigured")
            elif provider == "Ollama":
                status_label = "Available" if ollama_online else "Unavailable"
            else:
                status_label = "Unknown"

            models.append({
                "model_id": r[0],
                "provider": provider,
                "model_name": r[2],
                "model_type": r[3],
                "runtime_type": r[4],
                "enabled": enabled,
                "priority": r[6],
                "is_primary": is_primary,
                "is_fallback": is_fallback,
                "temperature": float(r[9]) if r[9] is not None else 0.2,
                "max_tokens": r[10] or 4096,
                "description": r[11] or "",
                "status": status_label,
                "created_at": r[12].isoformat() if r[12] else None,
                "updated_at": r[13].isoformat() if r[13] else None,
            })
        return models
    finally:
        cursor.close()
        conn.close()


def get_ai_model_by_id(model_id: int) -> Optional[Dict[str, Any]]:
    """Retrieves a single model by ID."""
    ensure_ai_models_table()
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            """
            SELECT
                MODEL_ID,
                PROVIDER,
                MODEL_NAME,
                MODEL_TYPE,
                RUNTIME_TYPE,
                ENABLED,
                PRIORITY,
                IS_PRIMARY,
                IS_FALLBACK,
                TEMPERATURE,
                MAX_TOKENS,
                DESCRIPTION,
                CREATED_AT,
                UPDATED_AT
            FROM GSVAI_AI_MODELS
            WHERE MODEL_ID = :model_id
            """,
            {"model_id": model_id},
        )
        r = cursor.fetchone()
        if not r:
            return None

        return {
            "model_id": r[0],
            "provider": r[1],
            "model_name": r[2],
            "model_type": r[3],
            "runtime_type": r[4],
            "enabled": bool(r[5]),
            "priority": r[6],
            "is_primary": bool(r[7]),
            "is_fallback": bool(r[8]),
            "temperature": float(r[9]) if r[9] is not None else 0.2,
            "max_tokens": r[10] or 4096,
            "description": r[11] or "",
            "created_at": r[12].isoformat() if r[12] else None,
            "updated_at": r[13].isoformat() if r[13] else None,
        }
    finally:
        cursor.close()
        conn.close()


def create_ai_model(model_data: Dict[str, Any], current_user_id: str = "admin") -> Dict[str, Any]:
    """
    Creates a new model in GSVAI_AI_MODELS with full validation and transactional safety.
    """
    ensure_ai_models_table()

    provider = (model_data.get("provider") or "").strip()
    model_name = (model_data.get("model_name") or "").strip()
    model_type = (model_data.get("model_type") or "LLM").strip().upper()
    priority = int(model_data.get("priority", 1))
    enabled = 1 if model_data.get("enabled", True) else 0
    is_primary = 1 if model_data.get("is_primary", False) else 0
    is_fallback = 1 if model_data.get("is_fallback", False) else 0
    temperature = float(model_data.get("temperature", 0.20))
    max_tokens = int(model_data.get("max_tokens", 4096))
    description = (model_data.get("description") or "").strip()

    # Validations
    if provider not in SUPPORTED_PROVIDERS:
        raise ValueError(f"Provider '{provider}' is not supported. Supported providers are: {', '.join(SUPPORTED_PROVIDERS)}")

    if not model_name:
        raise ValueError("Model name cannot be empty.")

    if model_type not in SUPPORTED_MODEL_TYPES:
        raise ValueError(f"Model type '{model_type}' is not supported. Supported types: {', '.join(SUPPORTED_MODEL_TYPES)}")

    if priority < 1:
        raise ValueError("Priority must be 1 or greater.")

    if is_primary and is_fallback:
        raise ValueError("A model cannot simultaneously be designated as both Primary and Fallback.")

    if is_primary and not enabled:
        raise ValueError("Cannot set a disabled model as primary.")

    if is_fallback and not enabled:
        raise ValueError("Cannot set a disabled model as fallback.")

    runtime_type = "API" if provider == "Groq" else "LOCAL"

    conn = get_connection()
    cursor = conn.cursor()
    try:
        # Check duplicate
        cursor.execute(
            "SELECT COUNT(*) FROM GSVAI_AI_MODELS WHERE UPPER(PROVIDER) = UPPER(:provider) AND UPPER(MODEL_NAME) = UPPER(:model_name)",
            {"provider": provider, "model_name": model_name},
        )
        if cursor.fetchone()[0] > 0:
            raise ValueError(f"Model '{model_name}' for provider '{provider}' is already configured in the registry.")

        # If primary requested, clear existing primary
        if is_primary:
            cursor.execute("UPDATE GSVAI_AI_MODELS SET IS_PRIMARY = 0 WHERE IS_PRIMARY = 1")

        # If fallback requested, clear existing fallback
        if is_fallback:
            cursor.execute("UPDATE GSVAI_AI_MODELS SET IS_FALLBACK = 0 WHERE IS_FALLBACK = 1")

        out_id = cursor.var(int)
        cursor.execute(
            """
            INSERT INTO GSVAI_AI_MODELS (
                PROVIDER, MODEL_NAME, MODEL_TYPE, RUNTIME_TYPE,
                ENABLED, PRIORITY, IS_PRIMARY, IS_FALLBACK,
                TEMPERATURE, MAX_TOKENS, DESCRIPTION,
                CREATED_AT, UPDATED_AT
            ) VALUES (
                :provider, :model_name, :model_type, :runtime_type,
                :enabled, :priority, :is_primary, :is_fallback,
                :temperature, :max_tokens, :description,
                SYSTIMESTAMP, SYSTIMESTAMP
            ) RETURNING MODEL_ID INTO :out_id
            """,
            {
                "provider": provider,
                "model_name": model_name,
                "model_type": model_type,
                "runtime_type": runtime_type,
                "enabled": enabled,
                "priority": priority,
                "is_primary": is_primary,
                "is_fallback": is_fallback,
                "temperature": temperature,
                "max_tokens": max_tokens,
                "description": description,
                "out_id": out_id,
            },
        )
        new_model_id = out_id.getvalue()[0]
        conn.commit()

        log_audit_event(
            action="MODEL_CREATED",
            resource_type="AI_MODEL",
            resource_id=str(new_model_id),
            user_id=current_user_id,
            details={
                "provider": provider,
                "model_name": model_name,
                "model_type": model_type,
                "priority": priority,
                "is_primary": bool(is_primary),
                "is_fallback": bool(is_fallback),
            },
            status="SUCCESS",
        )

        return get_ai_model_by_id(new_model_id)
    except Exception:
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()


def update_ai_model(model_id: int, updates: Dict[str, Any], current_user_id: str = "admin") -> Dict[str, Any]:
    """
    Updates configuration parameters for an existing model.
    Enforces primary/fallback exclusivity and safe updates.
    """
    existing = get_ai_model_by_id(model_id)
    if not existing:
        raise ValueError(f"AI Model with ID {model_id} not found.")

    conn = get_connection()
    cursor = conn.cursor()
    try:
        model_name = updates.get("model_name", existing["model_name"]).strip()
        if not model_name:
            raise ValueError("Model name cannot be empty.")

        priority = int(updates.get("priority", existing["priority"]))
        if priority < 1:
            raise ValueError("Priority must be 1 or greater.")

        temperature = float(updates.get("temperature", existing["temperature"]))
        max_tokens = int(updates.get("max_tokens", existing["max_tokens"]))
        description = updates.get("description", existing["description"])

        enabled = existing["enabled"]
        if "enabled" in updates:
            enabled = bool(updates["enabled"])

        is_primary = existing["is_primary"]
        if "is_primary" in updates:
            is_primary = bool(updates["is_primary"])

        is_fallback = existing["is_fallback"]
        if "is_fallback" in updates:
            is_fallback = bool(updates["is_fallback"])

        # Constraints
        if is_primary and is_fallback:
            raise ValueError("A model cannot simultaneously be designated as both Primary and Fallback.")

        if is_primary and not enabled:
            raise ValueError("Cannot set a disabled model as primary.")

        if is_fallback and not enabled:
            raise ValueError("Cannot set a disabled model as fallback.")

        # Disabling active primary check
        if existing["is_primary"] and not enabled:
            raise ValueError("Cannot disable the current primary model without selecting an active replacement.")

        # Atomic primary clearing
        if is_primary and not existing["is_primary"]:
            cursor.execute("UPDATE GSVAI_AI_MODELS SET IS_PRIMARY = 0 WHERE IS_PRIMARY = 1")

        # Atomic fallback clearing
        if is_fallback and not existing["is_fallback"]:
            cursor.execute("UPDATE GSVAI_AI_MODELS SET IS_FALLBACK = 0 WHERE IS_FALLBACK = 1")

        cursor.execute(
            """
            UPDATE GSVAI_AI_MODELS
            SET
                MODEL_NAME   = :model_name,
                PRIORITY     = :priority,
                ENABLED      = :enabled,
                IS_PRIMARY   = :is_primary,
                IS_FALLBACK  = :is_fallback,
                TEMPERATURE  = :temperature,
                MAX_TOKENS   = :max_tokens,
                DESCRIPTION  = :description,
                UPDATED_AT   = SYSTIMESTAMP
            WHERE MODEL_ID   = :model_id
            """,
            {
                "model_name": model_name,
                "priority": priority,
                "enabled": 1 if enabled else 0,
                "is_primary": 1 if is_primary else 0,
                "is_fallback": 1 if is_fallback else 0,
                "temperature": temperature,
                "max_tokens": max_tokens,
                "description": description,
                "model_id": model_id,
            },
        )
        conn.commit()

        log_audit_event(
            action="MODEL_UPDATED",
            resource_type="AI_MODEL",
            resource_id=str(model_id),
            user_id=current_user_id,
            details={
                "provider": existing["provider"],
                "model_name": model_name,
                "is_primary": is_primary,
                "is_fallback": is_fallback,
                "enabled": enabled,
            },
            status="SUCCESS",
        )

        return get_ai_model_by_id(model_id)
    except Exception:
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()


def enable_ai_model(model_id: int, current_user_id: str = "admin") -> Dict[str, Any]:
    """Enables an existing model."""
    existing = get_ai_model_by_id(model_id)
    if not existing:
        raise ValueError(f"AI Model with ID {model_id} not found.")

    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "UPDATE GSVAI_AI_MODELS SET ENABLED = 1, UPDATED_AT = SYSTIMESTAMP WHERE MODEL_ID = :model_id",
            {"model_id": model_id},
        )
        conn.commit()

        log_audit_event(
            action="MODEL_ENABLED",
            resource_type="AI_MODEL",
            resource_id=str(model_id),
            user_id=current_user_id,
            details={"provider": existing["provider"], "model_name": existing["model_name"]},
            status="SUCCESS",
        )
        return get_ai_model_by_id(model_id)
    finally:
        cursor.close()
        conn.close()


def disable_ai_model(model_id: int, current_user_id: str = "admin") -> Dict[str, Any]:
    """
    Disables an existing model.
    Forbids disabling the active primary model without a replacement.
    """
    existing = get_ai_model_by_id(model_id)
    if not existing:
        raise ValueError(f"AI Model with ID {model_id} not found.")

    if existing["is_primary"]:
        raise ValueError("Cannot disable the current primary model without selecting an active replacement.")

    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "UPDATE GSVAI_AI_MODELS SET ENABLED = 0, UPDATED_AT = SYSTIMESTAMP WHERE MODEL_ID = :model_id",
            {"model_id": model_id},
        )
        conn.commit()

        log_audit_event(
            action="MODEL_DISABLED",
            resource_type="AI_MODEL",
            resource_id=str(model_id),
            user_id=current_user_id,
            details={"provider": existing["provider"], "model_name": existing["model_name"]},
            status="SUCCESS",
        )
        return get_ai_model_by_id(model_id)
    finally:
        cursor.close()
        conn.close()


def set_primary_model(model_id: int, current_user_id: str = "admin") -> Dict[str, Any]:
    """
    Designates the chosen model as the single PRIMARY LLM.
    Enforces atomic transaction: clears previous primary, sets new primary.
    """
    existing = get_ai_model_by_id(model_id)
    if not existing:
        raise ValueError(f"AI Model with ID {model_id} not found.")

    if not existing["enabled"]:
        raise ValueError("Cannot set a disabled model as primary.")

    conn = get_connection()
    cursor = conn.cursor()
    try:
        # Atomic swap: clear existing primary and clear fallback on this model if it had it
        cursor.execute("UPDATE GSVAI_AI_MODELS SET IS_PRIMARY = 0 WHERE IS_PRIMARY = 1")
        cursor.execute(
            """
            UPDATE GSVAI_AI_MODELS
            SET IS_PRIMARY = 1, IS_FALLBACK = 0, UPDATED_AT = SYSTIMESTAMP
            WHERE MODEL_ID = :model_id
            """,
            {"model_id": model_id},
        )
        conn.commit()

        log_audit_event(
            action="MODEL_PRIMARY_CHANGED",
            resource_type="AI_MODEL",
            resource_id=str(model_id),
            user_id=current_user_id,
            details={"provider": existing["provider"], "model_name": existing["model_name"]},
            status="SUCCESS",
        )
        return get_ai_model_by_id(model_id)
    except Exception:
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()


def set_fallback_model(model_id: int, current_user_id: str = "admin") -> Dict[str, Any]:
    """
    Designates the chosen model as the single FALLBACK LLM.
    Enforces atomic transaction: clears previous fallback, sets new fallback.
    """
    existing = get_ai_model_by_id(model_id)
    if not existing:
        raise ValueError(f"AI Model with ID {model_id} not found.")

    if not existing["enabled"]:
        raise ValueError("Cannot set a disabled model as fallback.")

    if existing["is_primary"]:
        raise ValueError("Cannot set the active primary model as fallback.")

    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("UPDATE GSVAI_AI_MODELS SET IS_FALLBACK = 0 WHERE IS_FALLBACK = 1")
        cursor.execute(
            """
            UPDATE GSVAI_AI_MODELS
            SET IS_FALLBACK = 1, UPDATED_AT = SYSTIMESTAMP
            WHERE MODEL_ID = :model_id
            """,
            {"model_id": model_id},
        )
        conn.commit()

        log_audit_event(
            action="MODEL_FALLBACK_CHANGED",
            resource_type="AI_MODEL",
            resource_id=str(model_id),
            user_id=current_user_id,
            details={"provider": existing["provider"], "model_name": existing["model_name"]},
            status="SUCCESS",
        )
        return get_ai_model_by_id(model_id)
    except Exception:
        conn.rollback()
        raise
    finally:
        cursor.close()
        conn.close()


def delete_ai_model(model_id: int, current_user_id: str = "admin") -> Dict[str, Any]:
    """
    Deletes an AI model from GSVAI_AI_MODELS.
    Forbids deleting active primary or active fallback models.
    """
    existing = get_ai_model_by_id(model_id)
    if not existing:
        raise ValueError(f"AI Model with ID {model_id} not found.")

    if existing["is_primary"]:
        raise ValueError("Cannot delete the active primary model.")

    if existing["is_fallback"]:
        raise ValueError("Cannot delete the active fallback model.")

    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM GSVAI_AI_MODELS WHERE MODEL_ID = :model_id", {"model_id": model_id})
        conn.commit()

        log_audit_event(
            action="MODEL_DELETED",
            resource_type="AI_MODEL",
            resource_id=str(model_id),
            user_id=current_user_id,
            details={"provider": existing["provider"], "model_name": existing["model_name"]},
            status="SUCCESS",
        )
        return {"status": "SUCCESS", "message": f"Model '{existing['model_name']}' deleted successfully."}
    finally:
        cursor.close()
        conn.close()


def test_ai_model(model_id: int, current_user_id: str = "admin") -> Dict[str, Any]:
    """
    Executes a real connectivity and latency health test against the model.
    Never returns secrets, tokens, or system prompts.
    """
    existing = get_ai_model_by_id(model_id)
    if not existing:
        raise ValueError(f"AI Model with ID {model_id} not found.")

    provider = existing["provider"]
    model_name = existing["model_name"]
    start_time = time.time()

    if provider == "Groq":
        groq_api_key = os.getenv("GROQ_API_KEY")
        if not groq_api_key:
            return {
                "success": False,
                "provider": "Groq",
                "model": model_name,
                "latency_ms": 0,
                "error": "GROQ_API_KEY is not configured on the server.",
            }
        try:
            from groq import Groq
            client = Groq(api_key=groq_api_key)
            completion = client.chat.completions.create(
                model=model_name,
                messages=[{"role": "user", "content": "Respond with the single word: OK"}],
                max_completion_tokens=5,
                temperature=0.1,
            )
            latency_ms = int((time.time() - start_time) * 1000)
            log_audit_event(
                action="MODEL_TESTED",
                resource_type="AI_MODEL",
                resource_id=str(model_id),
                user_id=current_user_id,
                details={"provider": provider, "model": model_name, "success": True, "latency_ms": latency_ms},
                status="SUCCESS",
            )
            return {
                "success": True,
                "provider": "Groq",
                "model": model_name,
                "latency_ms": latency_ms,
                "message": f"Groq inference verified successfully ({latency_ms}ms).",
            }
        except Exception as e:
            latency_ms = int((time.time() - start_time) * 1000)
            err_msg = str(e)
            # Sanitize any key leakage in error messages
            if groq_api_key and groq_api_key in err_msg:
                err_msg = err_msg.replace(groq_api_key, "[REDACTED]")
            log_audit_event(
                action="MODEL_TESTED",
                resource_type="AI_MODEL",
                resource_id=str(model_id),
                user_id=current_user_id,
                details={"provider": provider, "model": model_name, "success": False, "latency_ms": latency_ms, "error": err_msg},
                status="FAILED",
            )
            return {
                "success": False,
                "provider": "Groq",
                "model": model_name,
                "latency_ms": latency_ms,
                "error": err_msg,
            }

    elif provider == "Ollama":
        ollama_endpoint = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
        try:
            resp = requests.post(
                f"{ollama_endpoint.rstrip('/')}/api/generate",
                json={
                    "model": model_name,
                    "prompt": "Respond with OK",
                    "stream": False,
                    "options": {"num_predict": 5, "temperature": 0.1},
                },
                timeout=10,
            )
            latency_ms = int((time.time() - start_time) * 1000)
            if resp.status_code == 200:
                log_audit_event(
                    action="MODEL_TESTED",
                    resource_type="AI_MODEL",
                    resource_id=str(model_id),
                    user_id=current_user_id,
                    details={"provider": provider, "model": model_name, "success": True, "latency_ms": latency_ms},
                    status="SUCCESS",
                )
                return {
                    "success": True,
                    "provider": "Ollama",
                    "model": model_name,
                    "latency_ms": latency_ms,
                    "message": f"Local Ollama inference verified successfully ({latency_ms}ms).",
                }
            else:
                err_msg = f"Ollama HTTP {resp.status_code}: {resp.text}"
                log_audit_event(
                    action="MODEL_TESTED",
                    resource_type="AI_MODEL",
                    resource_id=str(model_id),
                    user_id=current_user_id,
                    details={"provider": provider, "model": model_name, "success": False, "latency_ms": latency_ms, "error": err_msg},
                    status="FAILED",
                )
                return {
                    "success": False,
                    "provider": "Ollama",
                    "model": model_name,
                    "latency_ms": latency_ms,
                    "error": err_msg,
                }
        except Exception as e:
            latency_ms = int((time.time() - start_time) * 1000)
            err_msg = str(e)
            log_audit_event(
                action="MODEL_TESTED",
                resource_type="AI_MODEL",
                resource_id=str(model_id),
                user_id=current_user_id,
                details={"provider": provider, "model": model_name, "success": False, "latency_ms": latency_ms, "error": err_msg},
                status="FAILED",
            )
            return {
                "success": False,
                "provider": "Ollama",
                "model": model_name,
                "latency_ms": latency_ms,
                "error": f"Failed to connect to local Ollama at {ollama_endpoint}: {err_msg}",
            }
    else:
        return {
            "success": False,
            "provider": provider,
            "model": model_name,
            "latency_ms": 0,
            "error": f"Testing not supported for provider '{provider}'.",
        }
